version: '3.9'

services:
  catalog.api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DbSettings:mongo-url=mongodb://mongodb:27017"
    build:
      context: ../src/catalog/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  
  # infrastructures
  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
  
