version: '3.9'
name: e-commerce-microservice

services:
  catalog-api:
    container_name: catalog-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DbSettings:mongo-url=mongodb://mongodb:27017"
    build:
      context: ../src/services/catalog/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mongodb

  basket-api:
    container_name: basket-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Redis:url=redis:6379"
      - "GrpcSetting:DiscountUrl=http://discount-grpc"
    build:
      context: ../src/services
      dockerfile: ./basket/basket.api/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - redis
  
  discount-api:
    container_name: discount-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountDb=User ID=sa;Password=admin;Host=postgres;Port=5432;Database=discountDb"
    build:
      context: ../src/services/discount/discount.api
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - postgres
   
  discount-grpc:
    container_name: discount-grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DiscountDb=User ID=sa;Password=admin;Host=postgres;Port=5432;Database=discountDb"
    build:
      context: ../src/services/discount/discount.grpc
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    depends_on:
      - postgres

  order-api:
    container_name: order-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=sqlserver,1434;Database=OrderDb;User Id=sa;Password=testxoxo.;TrustServerCertificate=True;"
    build:
      context: ../src/services/ordering/
      dockerfile: Dockerfile
    ports:
      - "5004:80"
    depends_on:
      - sqlserver
  
  # infrastructures
  mongodb:
    image: "mongo:latest"
    container_name: catalog-db
    restart: always
    ports:
      - 27017:27017

  redis:
    image: "redis:alpine"
    container_name: basket-db
    restart: always
    ports:
      - 6379:6379

  portainer:
    image: "portainer/portainer-ce:2.19.0-alpine"
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
  
  postgres:
    image: "postgres:latest"
    container_name: discount-db
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data/
      
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/root/.pgadmin
   
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: order-db
    environment:
      - MSSQL_SA_PASSWORD=0tYKUl--tx0xo.
      - ACCEPT_EULA="Y"
    restart: always
    ports:
      - "1434:1433"